CFLAGS=-Wall -g

all: ex19

ex19: object.o



clean:
  rm -f ex19

  # make can't see anything in the file for object.o,
  # but it does see an object.c file,
  # and it knows how to turn a .c into a .o, so it does that.
